Q1='SELECT COUNT(ID) FROM MOVIE WHERE YEAR<2000'
Q2='SELECT AVG(RANK) FROM MOVIE WHERE YEAR=1991'
Q3='SELECT MIN(RANK) FROM MOVIE WHERE YEAR=1991'
Q5='SELECT COUNT(MOVIEWITHCAST.PID) FROM (ACTOR INNER JOIN CAST ON ID==PID) AS MOVIEWITHCAST WHERE MOVIEWITHCAST.FNAME="Jon"and MOVIEWITHCAST.LNAME="Dough"'
Q4='SELECT MOVIEWITHCAST.FNAME,MOVIEWITHCAST.LNAME FROM (ACTOR INNER JOIN CAST ON ID==PID) AS MOVIEWITHCAST WHERE MOVIEWITHCAST.MID=27'
Q6='SELECT NAME FROM MOVIE WHERE NAME LIKE "Young Latin Girls%" AND YEAR BETWEEN 2003 AND 2006'
Q7='''SELECT DIRECTOR.FNAME,DIRECTOR.LNAME FROM DIRECTOR INNER JOIN 
MOVIEDIRECTOR ON
`DIRECTOR`.ID=`MOVIEDIRECTOR`.DID INNER JOIN MOVIE ON 
`MOVIEDIRECTOR`.MID=`MOVIE`.ID WHERE MOVIE.NAME LIKE "STAR TREK%"'''

Q8='''SELECT MOVIE.NAME FROM MOVIE INNER JOIN MOVIEDIRECTOR ON 
`MOVIE`.ID==`MOVIEDIRECTOR`.MID INNER JOIN DIRECTOR ON `MOVIEDIRECTOR`.DID=`DIRECTOR`.ID 
INNER JOIN CAST ON `MOVIEDIRECTOR`.MID==`CAST`.MID INNER 
JOIN ACTOR ON `CAST`.PID=`ACTOR`.ID WHERE DIRECTOR.FNAME="Jackie (I)" AND DIRECTOR.LNAME="Chan" 
AND ACTOR.FNAME="Jackie (I)" AND ACTOR.LNAME="Chan"'''
Q9='''SELECT FNAME,LNAME FROM DIRECTOR INNER JOIN MOVIEDIRECTOR ON `DIRECTOR`.ID==`MOVIEDIRECTOR`.DID INNER JOIN MOVIE ON `MOVIEDIRECTOR`.MID==`MOVIE`.ID WHERE `MOVIE`.YEAR=2001 GROUP BY DID HAVING COUNT(DID)>=4 ORDER BY FNAME,LNAME DESC'''
Q10='''SELECT GENDER,COUNT(ID) FROM ACTOR GROUP BY GENDER 
ORDER BY GENDER'''

Q11='''SELECT DISTINCT(A.NAME),B.NAME,A.RANK,A.YEAR FROM 
(MOVIE AS A INNER JOIN MOVIE AS B ON 
A.RANK==B.RANK AND A.YEAR==B.YEAR AND 
A.NAME<>B.NAME) ORDER BY A.NAME LIMIT 100'''

#Q12='SELECT ACTOR.FNAME,MOVIE.YEAR,RANK FROM ACTOR INNER JOIN CAST ON `ACTOR`.ID=`CAST`.PID INNER JOIN MOVIE ON `CAST`.MID==`MOVIE`.ID ORDER BY FNAME,YEAR DESC LIMIT 100'
Q12='SELECT ACTOR.FNAME,MOVIE.YEAR,AVG(RANK) FROM ACTOR INNER JOIN CAST ON `ACTOR`.ID=`CAST`.PID INNER JOIN MOVIE ON `CAST`.MID==`MOVIE`.ID GROUP BY ACTOR.ID,YEAR ORDER BY FNAME,YEAR DESC LIMIT 100'

Q13='''SELECT ACTOR.FNAME,DIRECTOR.FNAME,AVG(RANK) as SCORE FROM ACTOR INNER JOIN CAST ON `ACTOR`.ID==`CAST`.PID INNER JOIN MOVIE ON `CAST`.MID=`MOVIE`.ID
INNER JOIN MOVIEDIRECTOR ON `CAST`.MID==`MOVIEDIRECTOR`.MID INNER JOIN DIRECTOR ON 
`MOVIEDIRECTOR`.DID=`DIRECTOR`.ID group by ACTOR.id,DIRECTOR.ID HAVING COUNT(MOVIE.ID)>=5 ORDER BY SCORE DESC,
DIRECTOR.FNAME,ACTOR.FNAME DESC LIMIT 100'''


#select fname,id,(SELECT NAME FROM MOVIE AS M INNER JOIN MOVIEDIRECTOR MD ON M.ID==MD.MID where MD.DID=d.id ORDER BY RANK DESC,NAME ASC LIMIT 1) from director d limit 100 