Q1='SELECT pid AS actor_id,COUNT(mid) AS no_of_movies FROM CAST GROUP BY pid'
Q2='SELECT year,COUNT(id) as COUNT FROM MOVIE GROUP BY YEAR ORDER BY YEAR'
Q3='SELECT YEAR,AVG(RANK) AS avg_rank FROM MOVIE GROUP BY YEAR HAVING COUNT(ID)>=10 ORDER BY YEAR DESC'
Q4='SELECT YEAR,MAX(RANK) AS max_rank FROM MOVIE GROUP BY YEAR ORDER BY YEAR'
Q5='SELECT RANK,COUNT(ID) AS no_of_movies FROM MOVIE WHERE NAME LIKE "a%" GROUP BY RANK'

